name: CI with Helm and GitHub OCI Registry

on:
  push:
    branches:
      - "*"

jobs:
  helm-and-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # # Set up Docker environment
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Docker Metadata action
      #   uses: docker/metadata-action@v4.3.0
      #   id: meta
      #   with:
      #     images: ghcr.io/${{ github.repository }}/picoblog
      #     tags: |
              # type=ref,event=branch
              # type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
              # type=raw,value=dev,enable=${{ github.ref != format('refs/heads/{0}', 'main') }}

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      # # Build and push Docker image to GitHub Container Registry
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      # Helm setup
      - name: Install Helm
        uses: azure/setup-helm@v3

      # Get the latest Helm chart values
      # - name: Get latest Helm chart values
      #   run: |
      #     helm repo add my-repo https://ghcr.io/${{ github.repository }}/helm
      #     helm repo update
      #     helm pull my-repo/picoblog --untar
      #     cp picoblog/values.yaml .

      # # Update chart version
      # - name: Update Helm chart version
      #   run: |
      #     CURRENT_VERSION=$(grep "version:" picoblog/Chart.yaml | cut -d " " -f2)
      #     NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$2++;print}')
      #     sed -i 's/version: $CURRENT_VERSION/version: $NEW_VERSION/' picoblog/Chart.yaml

      # # Update Helm values with digest
      # - name: Update Helm values with digest
      #   run: |
      #     DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ steps.meta.outputs.tags }})
      #     sed -i 's/digest: .*/digest: "$DIGEST"/' picoblog/values.yaml

      # - name: Push Helm chart to OCI compatible registry (Github)
      #   uses: bsord/helm-push@v4.2.0
      #   with:
      #     useOCIRegistry: true
      #     registry-url: oci://ghcr.io/${{ github.repository }}
      #     username: ${{ github.actor }}
      #     access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
      #     force: true
      #     chart-folder: .charts/picoblog

      # Push Helm chart to GitHub Container Registry
      - name: Push Helm chart
        run: |
          echo ${{ secrets.REGISTRY_ACCESS_TOKEN }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          cd .charts
          helm package picoblog
          ls -lah
          helm push picoblog-0.0.3.tgz oci://ghcr.io/${{ github.repository }}
